const menu = [
  {
    id: 1,
    title: 'Kadai Paneer ',
    category: 'Lunch',
    price: 15.99,
    img: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    desc: `Yummy Kadai Panner `
  {
    id: 2,
    title: 'Edli',
    category: 'Breakfast',
    price: 13.99,
    img: 'https://www.pexels.com/photo/cooked-rice-and-curry-food-served-on-white-plate-674574/',
    desc: `Made from urad dal and rice, this soft puff of rice is a healthy treat due to its lightness and its nutritional content. Idli is said to be light as it contains no fats, saturated fats or cholesterol. Further, it has merely 39 calories per piece, which seems measly to the 2,000-calorie daily requirement. `,
  },
  {
    id: 3,
    title: 'Dosa',
    category: 'Breakfast',
    price: 6.99,
    img: 'https://www.pexels.com/photo/platter-of-foods-941869/,
    desc: `vDosa is a fermented food which is easy to digest. Fermentation of foods increases the bioavailability of nutrients which helps the body to assimilate more nutrition`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Coffee',
    category: 'Beverages',
    price: 22.99,
    img: 'https://www.pexels.com/photo/close-up-of-coffee-cup-on-table-312418/,
    desc: `Coffee with added milk provides all the macro nutrients in good amounts; just one ounce of milk provides approximately 1.5 g of carbohydrates, 1g of protein and 1 gram of fat. Milk also provides essential micro nutrients like calcium, with 100 g of milk providing 123 mg of calcium`,
  },
  {
    id: 6,
    title: 'Tea',
    category: 'Beverages',
    price: 18.99,
    img: 'https://www.pexels.com/photo/brown-bread-on-brown-woven-basket-7936011/',
    desc: `Numerous studies have shown that a variety of teas may boost your immune system, fight off inflammation, and even ward off cancer and heart disease. While some brews provide more health advantages than others, there's plenty of evidence that regularly drinking tea can have a lasting impact on your wellness`,
  },
  {
    id: 7,
    title: 'Strawberry Shake',
    category: 'Beverages',
    price: 8.99,
    img: 'https://www.pexels.com/photo/strawberry-shake-103566/',
    desc: `Sugar provides instant energy to the brain to function properly. If you are going for a fruity milkshake-like Heritage Strawberry Milkshake, it is a good source of fibre too. Most fruits contain vitamin C which boosts immunity. `,
  },
  {
    id: 8,
    title: 'Gol-Gappe(Pani-puri)',
    category: 'Snacks',
    price: 12.99,
    img: 'https://www.pexels.com/photo/indian-dish-pani-puri-11574756/',
    desc: `Gol Gappe. The delicious snack of puris filled with tangy water is known as Gol Gappe in Northern India. Almost all of North India, except Haryana, refers to it as Gol Gappe  `,
  },
  {
    id: 9,
    title: 'Veg Biryani',
    category: 'Dinner',
    price: 16.99,
    img: 'https://www.pexels.com/photo/brown-and-gray-clay-serving-pots-2302809/',
    desc: `Vegetable biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices.`,
  },
];
export default menu;
